# Docker-compose file for running the application

version: '3.7'

services:
  front:
    build:
      context: ./front
    ports:
      - "3456:3456"
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    depends_on:
      - back
  back:
    build:
      context: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back/api:/app/api
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5656:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
volumes:
  pg_data: